// <auto-generated />
namespace PayRoll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixColumnNamingConvention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixColumnNamingConvention));
        
        string IMigrationMetadata.Id
        {
            get { return "202111210752249_FixColumnNamingConvention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
